updated css style text
Jacee94/petfeed pull request #15
Opened 2023-01-03 04:13 UTC by Rhondoid

2023-01-03 07:14 UTC, Jacee94 requested changes

2023-01-03 07:14 UTC, Jacee94 commented on controllers/htmlRoutes/createPostPageRoutes.js
> +
Can we remove this extra whitespace? Let's try to keep it pretty :)

2023-01-03 07:14 UTC, Jacee94 commented on controllers/htmlRoutes/createPostPageRoutes.js
> +
```suggestion
```

2023-01-03 07:14 UTC, Jacee94 commented on public/css/style.css
> +
```suggestion
```

2023-01-03 07:22 UTC, Jacee94 requested changes

2023-01-03 07:22 UTC, Jacee94 commented on public/css/tailwind.css
> +
If this is all our own custom styling shouldn't we keep it out of the tailwind.css and put it in our own css file?

2023-01-04 01:48 UTC, bikeller104 approved these changes

2023-01-04 01:48 UTC, Jacee94 approved these changes

2023-01-04 01:48 UTC, merged